# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Arun.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pywinauto import Desktop



class Ui_Arun(object):
    def setupUi(self, Arun):
        Arun.setObjectName("Arun")
        Arun.resize(637, 437)
        Arun.setMinimumSize(QtCore.QSize(0, 301))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(20)
        Arun.setFont(font)
        Arun.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Arun.setFocusPolicy(QtCore.Qt.StrongFocus)
        Arun.setWindowTitle("FLAMES   JUST for  FUN !!!!")
        icon = QtGui.QIcon()
        # try:
        icon.addPixmap(QtGui.QPixmap("code (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        # except:
        # icon.addPixmap(QtGui.QPixmap(".icon\\code (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Arun.setWindowIcon(icon)
        Arun.setWindowOpacity(2.0)
        Arun.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label1 = QtWidgets.QLabel(Arun)
        self.label1.setGeometry(QtCore.QRect(150, 10, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label1.setFont(font)
        self.label1.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label = QtWidgets.QLabel(Arun)
        self.label.setGeometry(QtCore.QRect(20, 140, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Arun)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Arun)
        self.pushButton.setGeometry(QtCore.QRect(170, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(172, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Arun)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(172, 255, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Arun)
        self.lineEdit.setGeometry(QtCore.QRect(360, 140, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("background-color: rgba(165, 245, 122, 228);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Arun)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 200, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("background-color: rgba(165, 245, 122, 228);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Arun)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(172, 255, 127);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Arun)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(172, 255, 127);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Arun)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 380, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(172, 255, 127);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(Arun)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 141, 121))
        self.label_3.setMinimumSize(QtCore.QSize(111, 0))
        self.label_3.setText("")
        # try:
        self.label_3.setPixmap(QtGui.QPixmap("man2.jpg"))
        # except:
        # self.label_3.setPixmap(QtGui.QPixmap(".img\\man2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Arun)
        self.label_4.setGeometry(QtCore.QRect(150, 50, 80, 80))
        self.label_4.setText("")
        # try:
        self.label_4.setPixmap(QtGui.QPixmap("p1.jpg"))
        # except:
        # self.label_4.setPixmap(QtGui.QPixmap(".img\\p1.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Arun)
        self.label_5.setGeometry(QtCore.QRect(230, 50, 80, 80))
        self.label_5.setText("")
        # try:
        self.label_5.setPixmap(QtGui.QPixmap("p2.jpg"))
        # except:
        # self.label_5.setPixmap(QtGui.QPixmap(".img\\p2.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Arun)
        self.label_6.setGeometry(QtCore.QRect(550, 50, 80, 80))
        self.label_6.setText("")
        # try:
        self.label_6.setPixmap(QtGui.QPixmap("p6.jpg"))
        # except:
        # self.label_6.setPixmap(QtGui.QPixmap(".img\\p6.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Arun)
        self.label_7.setGeometry(QtCore.QRect(310, 50, 80, 80))
        self.label_7.setText("")
        # try:
        self.label_7.setPixmap(QtGui.QPixmap("p3.jpg"))
        # except:
        # self.label_7.setPixmap(QtGui.QPixmap(".img\\p3.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Arun)
        self.label_8.setGeometry(QtCore.QRect(470, 50, 80, 80))
        self.label_8.setText("")
        # try:
        self.label_8.setPixmap(QtGui.QPixmap("p5.jpg"))
        # except:
        # self.label_8.setPixmap(QtGui.QPixmap(".img\\p5.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Arun)
        self.label_9.setGeometry(QtCore.QRect(390, 50, 80, 80))
        self.label_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_9.setText("")
        # try:
        self.label_9.setPixmap(QtGui.QPixmap("p4.jpg"))
        # except:
        # self.label_9.setPixmap(QtGui.QPixmap(".img\\p4.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Arun)
        self.label_10.setGeometry(QtCore.QRect(20, 320, 611, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setLineWidth(4)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Arun)
        self.label_11.setGeometry(QtCore.QRect(570, 280, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Arun)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)
        self.pushButton_2.clicked.connect(self.StopDef)
        self.pushButton_2.clicked.connect(self.label_10.clear)
        self.pushButton_3.clicked.connect(self.StopDef)
        self.pushButton_4.clicked.connect(self.FSDef)
        self.pushButton_5.clicked.connect(self.SSDef)

        self.pushButton.clicked.connect(self.proceedDef)

        #self.closeEvent(self.StopDef(Arun))


        QtCore.QMetaObject.connectSlotsByName(Arun)

    def proceedDef(self,Arun):
        gettext1 = self.lineEdit.text()
        gettext2 = self.lineEdit_2.text()
        if gettext2 == "" or gettext1 == "":
            error_ = QtWidgets.QErrorMessage()
            error_.showMessage("Please Enter Correct Input")
            error_.setWindowTitle("Error")
            error_.exec_()
            return

        Your_Name = gettext1
        Your_Partner_Name = gettext2

        li1 = []
        li2 = []
        for letter in Your_Name.lower():
            li1.append(letter)
        for letter in Your_Partner_Name.lower():
            li2.append(letter)

        li3 = []
        li4 = []
        for i in li1:
            if i in li2:
                li2.remove(i)
                li3.append(i)
        for i in li3:
            li1.remove(i)

        li4 = li1 + li2

        x = len(li4)  # 5
        if x == 0:
            error_ = QtWidgets.QErrorMessage()
            error_.showMessage("As Per FLAMES Rules , All letters are striked ,so not able to next move ,sorry!!")
            error_.setWindowTitle("Error")
            error_.exec_()
            return
        start_pos = 0
        li5 = ['f', 'l', 'a', 'm', 'e', 's']

        if x > len(li5):
            x = x - len(li5)
        while len(li5) != 1:
            y = start_pos + x
            while y > len(li5):
                y -= len(li5)
            li5.remove(li5[y - 1])
            start_pos = y - 1
            x = len(li4)

        global flamesResult
        flamesResult = ""
        if li5[0] == "f":
            flamesResult = (Your_Name + ' and ' + Your_Partner_Name + " are friends")
        if li5[0] == "l":
            flamesResult = (Your_Name + ' and  ' + Your_Partner_Name + " are lovers")
        if li5[0] == "a":
            flamesResult = (Your_Name + ' and  ' + Your_Partner_Name + " are  in Affection")
        if li5[0] == "m":
            flamesResult = (Your_Name + ' and  ' + Your_Partner_Name + " get Marriage")
        if li5[0] == "e":
            flamesResult = (Your_Name + ' and  ' + Your_Partner_Name + " are Enemies")
        if li5[0] == "s":
            flamesResult = (Your_Name + ' and  ' + Your_Partner_Name + " are Siblings")

        # print(flamesResult)
        #Calling Scroll Program
        global Scroll
        Scroll = True
        self.Sc(Arun)
        return



    global SCTime
    SCTime=1000

    global win
    win = True

    def Sc(self,Arun):
        global Scroll

        fr = flamesResult
        # 0-53
        spac = ""
        spacNo=65
        for i in range(spacNo):
            spac = spac + " "

        fr = spac + fr
        lefr = len(fr)
        no = 0
        while Scroll==True:
            # self.checkWindow(Arun)
            windows = Desktop(backend="uia").windows()
            # # print([w.window_text() for w in windows])
            if not "FLAMES   JUST for  FUN !!!!" in [w.window_text() for w in windows]:
                break

            getlabeltext = self.label_11.text()
            SCtime = (float(getlabeltext[:-1]) * 1000)

            loop = QtCore.QEventLoop()
            QtCore.QTimer.singleShot(SCtime, loop.quit)

            _translate = QtCore.QCoreApplication.translate
            self.label_10.setText(_translate("Arun", fr[no:no + spacNo]))
            # print(fr[no:no + spacNo])
            if no >= lefr:
                no = 0
            else:
                no = no + 1
            # print(2)
            # app.aboutToQuit.connect(self.StopDef(Arun))
            # print(sys.exit)
            # if not sys.exit:
            #     print("ok")
            #     break
            # self.checkWindow(Arun)
            # global win
            # if win==False:
            #     # sys.exit
            #     break
            loop.exec()

        return

    def checkWindow(self,Arun):
        global win
        win=True
        windows = Desktop(backend="uia").windows()
        # print([w.window_text() for w in windows])
        if not "FLAMES   JUST for  FUN !!!!" in [w.window_text()for w in windows]:
            win=False
        return

    def StopDef(self,Arun):
        global Scroll
        Scroll=False
        return

    def FSDef(self,Arun):
        # print("start")

        getlabeltext=self.label_11.text()
        # print(getlabeltext[:-1])
        if (float(getlabeltext[:-1])*1000)-50<=0.0:
            return
        SCTime=(float(getlabeltext[:-1])*1000)-50

        _translate = QtCore.QCoreApplication.translate
        lbltext = str(SCTime / 1000) + "x"
        # print(lbltext)
        self.label_11.setText(_translate("Arun",lbltext))
        # print("end")
        return


    def SSDef(self,Arun):
        # print("start")

        getlabeltext = self.label_11.text()
        # print(getlabeltext[:-3])
        SCTime = (float(getlabeltext[:-1]) * 1000) + 50
        _translate = QtCore.QCoreApplication.translate
        lbltext=str(SCTime/1000)+"x"
        # print(lbltext)
        self.label_11.setText(_translate("Arun", lbltext))
        # print("end")
        return


    def retranslateUi(self, Arun):
        _translate = QtCore.QCoreApplication.translate
        self.label1.setText(_translate("Arun", "<html><head/><body><p><span style=\" color:#0000ff;\">WELCOME TO FLAMES</span></p></body></html>"))
        self.label.setText(_translate("Arun", "Your Name"))
        self.label_2.setText(_translate("Arun", "Your\'s Partner Name"))
        self.pushButton.setText(_translate("Arun", "Proceed"))
        self.pushButton_2.setText(_translate("Arun", "Reset"))
        self.pushButton_3.setText(_translate("Arun", "Stop"))
        self.pushButton_4.setText(_translate("Arun", "Fast scroll"))
        self.pushButton_5.setText(_translate("Arun", "Slow scroll"))
        # self.label_10.setText(_translate("Arun", "1  x"))
        self.label_11.setText(_translate("Arun", "0.3x"))

    # def __init__(self):
    #     super(QtWidgets.QWidget).__init__()

    def closeEvent(self,event):

        # print(1)
        global Scroll
        Scroll=False




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    Arun = QtWidgets.QDialog()
    ui = Ui_Arun()
    ui.setupUi(Arun)

    Arun.show()

    ret=app.exec_()
    # print("Yes")
    Ui_Arun.closeEvent(Arun, event=True)
    sys.exit(ret)

